### ISSUE TITLE
Example usage in rails controller?

### ISSUE THREAD

**Issue by kevincolten** [tomasc/dragonfly_chrome_headless#2]
Do you have any examples integrating it with a Rails controller? Is the API similar to something like https://github.com/mileszs/wicked_pdf/?

**Comment by tomasc** [comment]
@kevincolten this is a [Dragonfly](https://github.com/markevans/dragonfly) plugin, please look into the basics of use over there.

**Comment by tomasc** [comment]
@kevincolten there's new gem for this purpose now https://github.com/tomasc/dragonfly_puppeteer
